- name: "Build Status"
  shield: "github/actions/workflow/status/chirag127/SystemAudioTranscriber-RealTime-SystemAudio-To-Text-Windows-App/ci.yml?branch=main&style=flat-square"
  logo: "github"
  alt: "Build Status"
- name: "Code Coverage"
  shield: "codecov/c/github/chirag127/SystemAudioTranscriber-RealTime-SystemAudio-To-Text-Windows-App?style=flat-square"
  logo: "codecov"
  alt: "Code Coverage"
- name: "TypeScript Version"
  shield: "badge/typescript-6.x-blue?style=flat-square&logo=typescript"
  alt: "TypeScript Version"
- name: "Vite Version"
  shield: "badge/vite-7-blueviolet?style=flat-square&logo=vite"
  alt: "Vite Version"
- name: "License"
  shield: "github/license/chirag127/SystemAudioTranscriber-RealTime-SystemAudio-To-Text-Windows-App?style=flat-square"
  logo: "github"
  alt: "License"
- name: "GitHub Stars"
  shield: "github/stars/chirag127/SystemAudioTranscriber-RealTime-SystemAudio-To-Text-Windows-App?style=flat-square&logo=github"
  alt: "GitHub Stars"
